[package]
name = "sparktext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"

[dev-dependencies]
ordered-float = "3.7.0"
rust_decimal = "1.29.1"
rust_decimal_macros = "1.29.1"
